/**
 * Rankings archive — read API for snapshotted rankings.
 *
 * Every rankings refresh writes a dated snapshot into
 * `src/data/rankings-archive/{men,women}/YYYY-MM-DD.ts`. A per-gender
 * `index.ts` (auto-regenerated by `scripts/snapshot-rankings.ts`) rolls
 * those snapshots up into a `Record<date, snapshot>` map plus a
 * `latestDate` pointer.
 *
 * `src/data/active-rankings.json` records which snapshot (per gender) is
 * currently pinned for the Regional Predictions page. `null` means "use
 * latest". The pin is set via `scripts/set-active-rankings.ts`; the
 * refresh pipeline never touches it.
 *
 * Consumer rules of thumb:
 *   - Regional Predictions page (and anything downstream of it that reads
 *     rankings directly) → loadActive(gender)
 *   - Teams pages, historical results, conference championships, records
 *     → keep the existing `@/data/rankings-{men,women}` import (= latest)
 *   - One-off tooling that needs a specific date → loadSnapshot(...)
 */

import type { TeamData } from "@/data/rankings-men";
import { archiveMen, latestDateMen } from "@/data/rankings-archive/men";
import { archiveWomen, latestDateWomen } from "@/data/rankings-archive/women";
import activeRankingsConfig from "@/data/active-rankings.json";

export type Gender = "men" | "women";

/**
 * A single dated snapshot of rankings for one gender. `teams` is a full
 * `TeamData[]` array — same shape as the live `rankings-{men,women}.ts`
 * file. Optional fields on `TeamData` (avgPoints, strengthOfSchedule,
 * etc.) MAY be absent on older / backfilled snapshots; consumers should
 * tolerate `undefined`.
 */
export interface RankingsSnapshot {
  date: string;          // ISO date, YYYY-MM-DD
  gender: Gender;
  pulledAt: string;      // ISO timestamp from the original Clippd pull
  label: string | null;  // optional human label, e.g. "frozen-for-regionals"
  source: string;        // provenance, e.g. "clippd-leaderboard-api"
  teams: TeamData[];
}

/**
 * Pin record for one gender in `active-rankings.json`. `null` (at the
 * top level) means "no pin set, use latest".
 */
export interface ActivePin {
  date: string;          // YYYY-MM-DD
  label: string | null;
  setAt: string;         // ISO timestamp
  setBy: string | null;  // human attribution (e.g. "David Tenneson")
}

export interface ActiveRankingsConfig {
  men: ActivePin | null;
  women: ActivePin | null;
}

const config = activeRankingsConfig as ActiveRankingsConfig;

function archive(gender: Gender): Record<string, RankingsSnapshot> {
  return gender === "men" ? archiveMen : archiveWomen;
}

function latestDate(gender: Gender): string | null {
  return gender === "men" ? latestDateMen : latestDateWomen;
}

/**
 * Returns the rankings array currently shown by the Regional Predictions
 * page for `gender`. If a pin is configured in active-rankings.json,
 * returns that snapshot's teams; otherwise falls back to the latest
 * snapshot. Throws if the archive is empty (= bootstrap state).
 */
export function loadActive(gender: Gender): TeamData[] {
  return loadActiveSnapshot(gender).teams;
}

/**
 * Like {@link loadActive} but returns the full snapshot envelope so the
 * caller can read `date`, `pulledAt`, and `label` (e.g. for an "as of"
 * banner on the page). Throws if the archive is empty.
 */
export function loadActiveSnapshot(gender: Gender): RankingsSnapshot {
  const pin = config[gender];
  if (pin) {
    const snap = archive(gender)[pin.date];
    if (!snap) {
      throw new Error(
        `active-rankings.json pins ${gender} to ${pin.date} but no archive ` +
          `entry exists for that date. Either run the seed or update the pin.`
      );
    }
    return snap;
  }
  return loadLatestSnapshot(gender);
}

/**
 * Returns the most recent snapshot's teams for `gender`. Used by pages
 * that should always reflect the latest data (Teams, /regionals
 * historical, etc.) — though those currently use the direct
 * `@/data/rankings-{men,women}` import, which is functionally
 * equivalent.
 */
export function loadLatest(gender: Gender): TeamData[] {
  return loadLatestSnapshot(gender).teams;
}

export function loadLatestSnapshot(gender: Gender): RankingsSnapshot {
  const date = latestDate(gender);
  if (!date) {
    throw new Error(
      `rankings archive for ${gender} is empty — cannot load latest.`
    );
  }
  const snap = archive(gender)[date];
  if (!snap) {
    throw new Error(
      `rankings archive index for ${gender} points at ${date} but no ` +
        `snapshot file exists. Re-run scripts/snapshot-rankings.ts ` +
        `--regen-index.`
    );
  }
  return snap;
}

export function loadSnapshot(
  gender: Gender,
  date: string
): RankingsSnapshot | null {
  return archive(gender)[date] ?? null;
}

export function listSnapshots(gender: Gender): string[] {
  return Object.keys(archive(gender)).sort();
}

export function getActivePin(gender: Gender): ActivePin | null {
  return config[gender];
}
