// Re-exports the generated records-women.json with the correct type.
// Generated by scripts/build-records.ts.

import type { RecordBook } from "./records-types";
import data from "./records-women.json";

export const recordsWomen = data as RecordBook;
