// Re-exports the generated records-men.json with the correct type.
// Generated by scripts/build-records.ts.

import type { RecordBook } from "./records-types";
import data from "./records-men.json";

export const recordsMen = data as RecordBook;
